INSERT INTO SOCIO_TORCEDOR (ID_SOCIO, NOME_SOCIO, EMAIL, DATA_NASCIMENTO, TIME_CORACAO) VALUES (1, 'Rodrigo Lima',	   'rodrigo@app.com', TO_DATE('2017-08-01', 'YYYY-MM-DD'), 'Santo Andre');
INSERT INTO SOCIO_TORCEDOR (ID_SOCIO, NOME_SOCIO, EMAIL, DATA_NASCIMENTO, TIME_CORACAO) VALUES (2, 'Felipe Lima', 	   'fl@hotmail.com', TO_DATE('2017-08-01', 'YYYY-MM-DD'), 'Sao Bernardo');

INSERT INTO TIMECORACAO (ID_TIMECORACAO, NOME) VALUES (1, 'Santo Andre');
INSERT INTO TIMECORACAO (ID_TIMECORACAO, NOME) VALUES (2, 'Sao Bernardo');